apiVersion: v1
kind: Secret
metadata:
  name: trino-secrets
  namespace: nexoryx-trino
type: Opaque
stringData:
  POSTGRES_DB: metastore
  POSTGRES_USER: trino
  POSTGRES_PASSWORD: CHANGE_ME
  MINIO_ROOT_USER: admin
  MINIO_ROOT_PASSWORD: CHANGE_ME
