apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-coordinator
  namespace: nexoryx-trino
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trino-coordinator
  template:
    metadata:
      labels:
        app: trino-coordinator
    spec:
      containers:
      - name: trino
        image: trinodb/trino:448
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config
          mountPath: /etc/trino
        readinessProbe:
          httpGet:
            path: /v1/info
            port: 8080
          initialDelaySeconds: 20
        livenessProbe:
          httpGet:
            path: /v1/info
            port: 8080
          initialDelaySeconds: 60
      volumes:
      - name: config
        configMap:
          name: trino-config
---
apiVersion: v1
kind: Service
metadata:
  name: trino-coordinator
  namespace: nexoryx-trino
spec:
  selector:
    app: trino-coordinator
  ports:
  - port: 8080
