apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: nexoryx-trino
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trino-worker
  template:
    metadata:
      labels:
        app: trino-worker
    spec:
      containers:
      - name: trino-worker
        image: trinodb/trino:448
        env:
        - name: DISCOVERY_URI
          value: http://trino-coordinator:8080
        resources:
          requests:
            cpu: "500m"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
